/* SWG ground command list for the macro builder's autocomplete.
   Base list from swgaide's command reference + Restoration staples.
   Not exhaustive — unknown commands are allowed, this only powers suggestions. */
const MACRO_COMMANDS = [
  '/accuse', '/ache', '/acidcone1', '/acidcone2', '/acidsingle1', '/acidsingle2', '/actionshot1',
  '/actionshot2', '/activateclone', '/addpower', '/adjust', '/adn', '/adrenalBoost', '/afk',
  '/afk4drink', '/afk4food', '/afkmessage', '/afktime', '/agree', '/aim', '/airguitar',
  '/alarmclock', '/alias', '/amazing', '/animalAttack', '/animalCalm', '/animalScare', '/anon',
  '/anxious', '/apologize', '/applaud', '/arch', '/areatrack', '/assist', '/attack', '/attend',
  '/autoDeclineDuel', '/avoidIncapacitation', '/ayt', '/backhand', '/bactaInfusion', '/bad',
  '/badfeeling', '/bah', '/bak', '/bandflourish', '/bandleader', '/bandPause', '/banfromstructure',
  '/bang', '/bark', '/bateyelashes', '/bbl', '/beam', '/beckon', '/belch', '/berserk2',
  '/berzerk1', '/bite', '/blame', '/bleed', '/bleedingshot', '/blink', '/blow', '/blowkiss',
  '/blush', '/bmoc', '/bob', '/bodyshot1', '/bodyshot2', '/bodyslam', '/boogle', '/bored',
  '/bounce', '/bouquet', '/bow', '/bow2', '/bow3', '/bow4', '/bowhead', '/brandish', '/brb',
  '/broadcastgalaxy', '/broadcastplanet', '/brt', '/burp', '/burstrun', '/bye', '/cackle',
  '/callretreat', '/callstop', '/calm', '/cancelCraftingSession', '/catchbreath', '/censor',
  '/centerofbeing', '/changeBandMusic', '/changeDance', '/channelForce', '/chargeshot1', '/chase',
  '/cheek', '/cheer', '/chestpuff', '/chortle', '/chuckle', '/claim', '/claimVeteranReward',
  '/clap', '/claw', '/clearQueue', '/clientMood', '/clientSocial', '/clone', '/closeContainer',
  '/closeeyes', '/coloredlights', '/combarea', '/combatAim', '/combatEscape', '/combatModeCheck',
  '/combatSpam', '/combatTarget', '/combhair', '/comfort', '/command', '/commandBrowser',
  '/community', '/con', '/conceal', '/concealshot', '/congratulate', '/consent', '/contemplate',
  '/conversationStart', '/conversationStop', '/corpse', '/cough', '/cover', '/covereyes', '/cower',
  '/createPrototype', '/cringe', '/cry', '/cuckoo', '/culater', '/curse', '/curtsey', '/customize',
  '/dance', '/dazzle', '/deathblow', '/declareresidence', '/deepbow', '/defend', '/demand',
  '/demure', '/denyservice', '/deride', '/destroystructure', '/dies', '/disagree', '/disband',
  '/diseaseInnoculation', '/dismount', '/distract', '/diveshot', '/doh', '/doubletap', '/down',
  '/dragplayer', '/drainForce', '/dream', '/droidtrack', '/drool', '/drop', '/duck', '/duel',
  '/dump', '/dumpPausedCommands', '/earth', '/echo', '/echuta', '/eek', '/eject', '/elbow',
  '/emboldenpets', '/embrace', '/emote', '/emptyHopper', '/encourage', '/endduel',
  '/endorphineInjection', '/enragepets', '/evilgrin', '/examine', '/exhausted', '/eyebrow',
  '/eyeshot', '/faint', '/false', '/faq', '/fastblast', '/fear', '/featuredSolo', '/feed', '/feel',
  '/feh', '/feigndeath', '/fiddle', '/fidget', '/find', '/findFriend', '/firejet', '/firstaid',
  '/firstpalm', '/fish', '/flail', '/flame', '/flashbomb', '/flee', '/flex', '/flip', '/flipcoin',
  '/flirt', '/flourish', '/flower', '/flutter', '/follow', '/followMe', '/fool', '/forage',
  '/forceMeditate', '/forceofwill', '/forceRun1', '/forceSpeed1', '/friend', '/friendpet',
  '/frown', '/fume', '/fuzzy', '/gag', '/gallop', '/gape', '/gasp', '/gawk', '/gaze', '/gcw',
  '/getSample', '/giggle', '/giverose', '/giveup', '/glare', '/gloat', '/glow', '/going',
  '/grantpermission', '/grantzoningrights', '/greet', '/grin', '/groan', '/group', '/groupChat',
  '/grouploot', '/groupSay', '/grovel', '/growl', '/grumble', '/grunt', '/gsay', '/gtell',
  '/guard', '/guild', '/guildsay', '/gulp', '/hack', '/hail', '/halfnelson', '/halo', '/hand',
  '/handshake', '/harvest', '/harvestcorpse', '/haveconsent', '/headache', '/headlock',
  '/healdamage', '/healstatesother', '/healStatesSelf', '/healwound', '/hearnoevil', '/helper',
  '/helpme', '/hero', '/hiccup', '/high5', '/hiss', '/hobble', '/holdon', '/holoemote', '/hop',
  '/hose', '/hot', '/hug', '/huge', '/hum', '/hunger', '/iffscramble', '/imfull', '/imitate',
  '/innate', '/innateregeneration', '/innocent', '/inquire', '/installmissionterminal',
  '/interrupt', '/intimidate', '/introduce', '/invite', '/isafk', '/itemmail', '/jam', '/jas',
  '/jediMindTrick', '/jk', '/join', '/jump', '/kipupshot', '/kiss', '/kisscheek', '/kneel',
  '/knockdownfire', '/knockwood', '/kowtow', '/lagging', '/large', '/lastditch', '/laugh', '/lean',
  '/leer', '/legshake', '/lfg', '/lick', '/lives', '/logout', '/logoutclient', '/lol', '/loot',
  '/lootAiCorpse', '/lootPlayerCorpse', '/loser', '/lost', '/lotto', '/love', '/luck', '/lure',
  '/macro', '/mails', '/makeLeader', '/manual', '/maskscent', '/medicalforage', '/meditate',
  '/medium', '/melt', '/mercy', '/mimic', '/mirror', '/missionBrowser', '/mock', '/model', '/mood',
  '/moods', '/mope', '/mosh', '/mount', '/mourn', '/move', '/moveFurniture',
  '/multitargetpistolshot', '/mutter', '/nails', '/namepet', '/nameStructure', '/nap', '/nausea',
  '/nelson', '/nextCraftingStage', '/no', '/nod', '/noogie', '/nose', '/note', '/nudge',
  '/nutrientInjection', '/nuzzle', '/omg', '/oneknee', '/openContainer', '/opossum',
  '/overchargeshot1', '/pant', '/pat', '/patrol', '/pause', '/pay', '/paymaintenance', '/payup',
  '/peer', '/peptalk', '/pet', '/peyoo', '/pickup', '/pillow', '/pinch', '/pistolmeleedefense1',
  '/plugears', '/plugnose', '/pointat', '/pointblankarea1', '/pointblanksingle1', '/pointdown',
  '/pointleft', '/pointright', '/poisonInnoculation', '/poke', '/polearm', '/ponder', '/pound',
  '/pout', '/powerboost', '/preen', '/primp', '/prod', '/prone', '/protect', '/provoke', '/pshrug',
  '/pucker', '/puke', '/pull', '/punch', '/push', '/puzzle', '/pvp', '/question', '/quiet',
  '/quit', '/raise', '/rasberry', '/ready', '/reassure', '/recite', '/recruitskilltrainer',
  '/release', '/repairdroiddeed', '/requestCraftingSession', '/rescue', '/resetfurniture',
  '/restartCraftingSession', '/retell', '/retort', '/retreat', '/reviveplayer',
  '/revokepermission', '/roar', '/rofl', '/roleplay', '/rolleyes', '/rollshot', '/rotate',
  '/rotateFurniture', '/rubnose', '/rude', '/ruffle', '/salute', '/sample', '/sampledna', '/say',
  '/scare', '/scared', '/scold', '/scowl', '/scratch', '/scream', '/seenoevil',
  '/selectDraftSchematic', '/serotoninInjection', '/service', '/set', '/setCurrentSkillTitle',
  '/setperform', '/setpermission', '/setprivacy', '/shake', '/sharpen', '/shiver', '/shoo',
  '/shout', '/shower', '/showpvprating', '/shrug', '/shudder', '/shush', '/sigh', '/sit',
  '/skills', '/skip', '/slap', '/slit', '/slobber', '/small', '/smell', '/smile', '/smirk',
  '/smokebomb', '/snap', '/snarl', '/sneak', '/sneer', '/sneeze', '/snicker', '/sniff', '/sniffle',
  '/snog', '/snore', '/snort', '/soapbox', '/softclap', '/spam', '/speaknoevil', '/spin', '/spit',
  '/spotlight', '/sprayshot', '/squeeze', '/squirm', '/stand', '/stare', '/startband',
  '/startdance', '/startmusic', '/startsong', '/stay', '/steadyaim', '/stink', '/stomp',
  '/stopBand', '/stopBleeding', '/stopdance', '/stopfollow', '/stopgallop', '/stopmusic',
  '/stopwatching', '/strafeshot1', '/strangle', '/stretch', '/structurestatus', '/strut',
  '/stunAttack', '/sulk', '/summon', '/suppressionfire1', '/surprised', '/surpriseshot',
  '/surrenderself', '/survey', '/swat', '/synchronizedUIListen', '/takecover', '/tame', '/target',
  '/targetAtCursor', '/targetAtCursorStop', '/targetGroup0', '/targetSelf', '/tell', '/thank',
  '/threaten', '/threatenshot', '/throwtrap', '/tip', '/tiphand', '/toggleAwayFromKeyBoard',
  '/touch', '/trade', '/train', '/transfer', '/transferItem', '/transferItemArmor',
  '/transferItemMisc', '/transferItemWeapon', '/tremble', '/trick1', '/trick2', '/true',
  '/tumbletokneeling', '/tumbletoprone', '/tumbletostanding', '/twiddle', '/twitch', '/ui',
  '/unbanfromstructure', '/unconsent', '/underhandshot', '/unstick', '/untarget', '/vendor',
  '/ventriloquism', '/veteran', '/volleyfire', '/wait', '/warcry1', '/warcry2', '/warningshot',
  '/watch', '/wave', '/wave2', '/waypoint', '/whisper', '/whistle', '/who', '/wiggle', '/wildshot',
  '/wince', '/wink', '/woowoo', '/worship', '/yawn', '/yes'
];

/* Usage hints for the commands people actually macro — args + a one-line plain-
   English note. Keyed by command (with leading slash). The long tail of commands
   has no entry and just shows its name; add entries here as they're confirmed.
   Angle-bracketed args are required, [square] are optional. */
const MACRO_USAGE = {
  '/pause': { args: '<seconds>', desc: 'Wait this many seconds before the next command (e.g. /pause 0.25).' },
  '/macro': { args: '<name>', desc: 'Run another macro by name — a macro that calls itself loops.' },
  '/dumpPausedCommands': { args: '', desc: 'Clear commands queued up behind pauses — common loop housekeeping.' },
  '/clearQueue': { args: '', desc: 'Empty the command queue.' },
  '/ui': { args: 'action <name>', desc: 'Fire a UI action, e.g. /ui action toolbarSlot00 or cycleTargetOutward.' },
  '/say': { args: '<text>', desc: 'Say text in spatial (local) chat.' },
  '/shout': { args: '<text>', desc: 'Shout — wider range than /say.' },
  '/gsay': { args: '<text>', desc: 'Send text to group chat.' },
  '/groupSay': { args: '<text>', desc: 'Send text to group chat.' },
  '/guild': { args: '<text>', desc: 'Send text to guild chat.' },
  '/tell': { args: '<name> <text>', desc: 'Private message a player by name.' },
  '/whisper': { args: '<text>', desc: 'Whisper to your current target.' },
  '/recite': { args: '<text>', desc: 'Recite text (used in entertainer flourishing routines).' },
  '/invite': { args: '[name]', desc: 'Invite your target (or a named player) to your group.' },
  '/join': { args: '', desc: 'Accept a pending group invitation.' },
  '/disband': { args: '[name]', desc: 'Leave the group, or remove a named member.' },
  '/target': { args: '<name>', desc: 'Target a player or creature by name.' },
  '/targetAtCursor': { args: '', desc: 'Target whatever is under the cursor.' },
  '/untarget': { args: '', desc: 'Drop your current target.' },
  '/assist': { args: '[name]', desc: "Target your target's target (or a named player's)." },
  '/follow': { args: '[name]', desc: 'Auto-follow your target or a named player.' },
  '/stopfollow': { args: '', desc: 'Stop following.' },
  '/attack': { args: '[name]', desc: 'Attack your current target (or a named one).' },
  '/peace': { args: '', desc: 'Leave combat / sheathe weapon.' },
  '/duel': { args: '<name>', desc: 'Challenge a player to a duel.' },
  '/sit': { args: '', desc: 'Sit down.' },
  '/stand': { args: '', desc: 'Stand up.' },
  '/kneel': { args: '', desc: 'Kneel.' },
  '/prone': { args: '', desc: 'Go prone.' },
  '/afk': { args: '[message]', desc: 'Flag yourself away-from-keyboard with an optional message.' },
  '/harvest': { args: '<resource>', desc: 'Harvest from a creature corpse (hide / meat / bone).' },
  '/tip': { args: '<name> <amount>', desc: 'Tip a player credits (add bank for wired tips).' },
  '/flourish': { args: '<1-8>', desc: 'Perform a dance/music flourish by number.' },
  '/startDance': { args: '<name>', desc: 'Begin a dance (e.g. /startDance basic).' },
  '/stopDance': { args: '', desc: 'Stop dancing.' },
  '/startMusic': { args: '<name>', desc: 'Begin playing a song.' },
  '/stopMusic': { args: '', desc: 'Stop playing music.' },
  '/startBand': { args: '<name>', desc: 'Start a band song.' },
  '/stopBand': { args: '', desc: 'Stop the band.' },
  '/setCurrentSkillTitle': { args: '<title>', desc: 'Set your displayed skill title.' },
  '/waypoint': { args: '<x> <y> [name]', desc: 'Create a waypoint at coordinates, optionally named.' },
  '/wp': { args: '<x> <y> [name]', desc: 'Short for /waypoint.' },
  '/loot': { args: '', desc: 'Loot your target corpse.' },
  '/lootCorpse': { args: '', desc: 'Loot all nearby corpses.' },
  '/burstRun': { args: '', desc: 'Sprint burst (has a cooldown).' },
  '/mount': { args: '', desc: 'Mount your called vehicle/pet.' },
  '/dismount': { args: '', desc: 'Get off your mount.' },
  '/examine': { args: '[name]', desc: 'Examine your target or a named object.' },
  '/trade': { args: '<name>', desc: 'Open a secure trade with a player.' },
  '/healDamage': { args: '[target]', desc: 'Heal health/action damage on yourself or your target.' },
  '/healWound': { args: '<bar>', desc: 'Heal a wound (health/action/mind or an attribute).' },
  '/tendWound': { args: '', desc: 'Medic wound-tending action.' },
  '/tendDamage': { args: '', desc: 'Medic damage-tending action.' },
  '/holoemote': { args: '<name>', desc: 'Play a holographic emote.' },
  '/moveFurniture': { args: '<fwd> <side> <up>', desc: 'Nudge targeted furniture while decorating.' },
  '/rotateFurniture': { args: '<degrees>', desc: 'Rotate targeted furniture.' },
  '/logout': { args: '', desc: 'Log out (safe-logout timer applies).' },
};
